# Generated by Django 6.0.3 on 2026-03-04 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('refill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='refill.refill'),
        ),
    ]
